NorthwindMVC/NorthwindMVC/Controllers/ShoppingController.cs
using NorthwindBusiness.Src;
using NorthwindModel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NorthwindMVC.Controllers
{
    public class ShoppingController : Controller
    {
        private ShoppingCartBusiness shoppingCartList = new ShoppingCartBusiness();
        /*!
         * Lista de produtos
         */
        public ActionResult ShoppingIndex()
        {
            List<ShoppingCartExtend> list = shoppingCartList.SelectList();
            return View(list);
        }
        /*!
         * 
         */
        private List<SelectListItem> CreateCustomerList()
        {
            var custumers = new CustomersBusiness();
            var table = custumers.SelectList();
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "Select...", Value = "0" });
            foreach (var item in table)
                list.Add(new SelectListItem() { Text = item.CompanyName, Value = item.CustomerID });
            return list;
        }
        /*!
         * Cria novo produto 
         */
        public ActionResult ShoppingCreate()
        {            
            ViewBag.Customers = CreateCustomerList();
            //
            var shoppingCart = new ShoppingCart();
            return View(shoppingCart);
        }
        /*!
         * Valida e adiciona novo produto na lista 
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingCreate(ShoppingCart shoppingCart)
        {
            //validacoes
            if (shoppingCart.CustomerID == "0")
            {
                ModelState.AddModelError("CustomerID", "Selecione opção a customer.");
            }            
            if (shoppingCart.Description.Length > 100)
            {
                ModelState.AddModelError("Description", "Descrição deve ter no maximo 100 caracteres.");
            }
            if (ModelState.IsValid)
            {
                shoppingCartList.InsertItem(shoppingCart);
                return RedirectToAction("ShoppingIndex");
            }
            else
            {
                ViewBag.Customers = CreateCustomerList();
                return View("ShoppingCreate", shoppingCart);                
            }
        }

        public ActionResult ShoppingEdit(int id)
        {
            ViewBag.Customers = CreateCustomerList();
            var item = shoppingCartList.SelectItem(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingEdit(ShoppingCart shoppingCart)
        {
            //validacoes
            if (shoppingCart.CustomerID == "0")
            {
                ModelState.AddModelError("CustomerID", "Selecione opção a customer.");
            }
            if (ModelState.IsValid)
            {
                shoppingCartList.UpdateItem(shoppingCart);
                return RedirectToAction("ShoppingIndex");
            }
            else
            {
                return View("ShoppingEdit", shoppingCart);
            }
        }

        public ActionResult ShoppingDelete(int id)
        {
            var item = shoppingCartList.SelectItem(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingDelete(ShoppingCart shoppingCart)
        {
            shoppingCartList.DeleteItem(shoppingCart.ShoppingCartID);
            return RedirectToAction("ShoppingIndex");
        }

        



    }
}

NorthwindMVC/NorthwindMVC/Controllers/ShoppingItemController.cs
using NorthwindBusiness.Src;
using NorthwindModel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NorthwindMVC.Controllers
{
    public class ShoppingItemController : Controller
    {
        private static int shoppingCartID;
        /*!
         * Mostra lista de items
         * @param id: identificador do carrinho de compras
         */
        public ActionResult ShoppingItemIndex(int id)
        {
            shoppingCartID = id;
            var shoppingCartBusiness = new ShoppingCartItemBusiness(shoppingCartID);
            var list = shoppingCartBusiness.SelectList();
            return View(list);
        }

        private void SetupView()
        {
            ViewBag.ShoppingCartID = shoppingCartID;
            var list1 = CreateCategoryList();
            list1[indexCategory].Selected = true;
            ViewBag.Categories = list1;
            ViewBag.Products = CreateProductList(indexCategory);
        }

        public ActionResult ShoppingItemCreate()
        {
            SetupView();
            var item = new ShoppingCartItem();            
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingItemCreate(ShoppingCartItem shoppingCartitem)
        {
            //validaçoes servidor
            var shoppingCartItemBusiness = new ShoppingCartItemBusiness(shoppingCartID);
            if (shoppingCartitem.ProductID == 0)
            {
                ModelState.AddModelError("ProductID", "Selecione um produto.");
            }
            if (shoppingCartitem.Quantity == 0)
            {                
                ModelState.AddModelError("Quantity", "Especifique a quantidade.");
            }
            if (ModelState.IsValid)
            {
                var productBusiness = new ProductsBusiness();
                var product = productBusiness.SelectItem(shoppingCartitem.ProductID);
                shoppingCartitem.UnitPrice = product.UnitPrice;
                shoppingCartitem.ShoppingCartID = shoppingCartID;
                shoppingCartItemBusiness.InsertItem(shoppingCartitem);
                return RedirectToAction("ShoppingItemIndex", new { id = shoppingCartID });
            }
            else
            {
                SetupView();
                return View("ShoppingItemCreate", shoppingCartitem);
            }
        }

        public ActionResult ShoppingItemEdit(int id1, int id2)
        {
            //ShoppingCartItem item = new ShoppingCartItem();
            //if (id.HasValue)
            //{
            //    var products = new ProductsBusiness();
            //    var product = products.SelectItem(id.Value);
            //    //item.ProductID = product.ProductID;
            //    //item.UnitPrice = product.UnitPrice;
            //}
            ViewBag.ShoppingCartID = shoppingCartID;

            var shoppingCart = new ShoppingCartItemBusiness(shoppingCartID);
            //ShoppingCartItem item = shoppingCart.SelectItem(id1);
            //if (id2 != 0)
            //{
            //    var products = new ProductsBusiness();
            //    var product = products.SelectItem(id2);
            //    //item.ProductID = product.ProductID;
            //    //item.UnitPrice = product.UnitPrice;
            //}
            //return View(item);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingItemEdit(ShoppingCartItem shoppingCartitem)
        {
            var shoppingCart = new ShoppingCartItemBusiness(shoppingCartID);
            shoppingCart.InsertItem(shoppingCartitem);
            return RedirectToAction("ShoppingItemIndex", new { id = shoppingCartID });
        }
        
        private static int indexCategory = 0;

        public ActionResult ShoppingItemSetProductID(int id)
        {
            indexCategory = id;            
            return RedirectToAction("ShoppingItemCreate");            
        }

        [HttpGet]
        public JsonResult ShoppingItemSetProductIdJson(int id)
        {
            indexCategory = id;            
            var list = CreateProductList(indexCategory);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        private List<SelectListItem> CreateCategoryList()
        {
            var category = new CategoriesBusiness();
            var table = category.SelectList();
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "All", Value = "0" });
            foreach (var item in table)
                list.Add(new SelectListItem() { Text = item.CategoryName, Value = item.CategoryID.ToString() });
            return list;
        }

        public List<SelectListItem> CreateProductList(int id)
        {
            var products = new ProductsBusiness();
            List<Product> list1 = new List<Product>();
            if (id == 0)
                list1 = products.SelectList();
            else
                list1 = products.SelectListByCategory(id);
            var list2 = new List<SelectListItem>();
            list2.Add(new SelectListItem() { Text = "Select", Value = "0" });
            foreach (var item in list1)
                list2.Add(new SelectListItem() { Text = item.ProductID.ToString("000") +"-"+ item.ProductName + "[" + item.UnitPrice + "]", Value = item.ProductID.ToString() });
            return list2;
        }

        [HttpGet]
        public JsonResult GetProductInfo(int id)
        {
            var products = new ProductsBusiness();
            var list = products.SelectListInfo(id);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

NorthwindMVC/NorthwindMVC/Views/Shopping/ShoppingCreate - bkp.cshtml
@model NorthwindModel.Models.ShoppingCart
@using NorthwindBusiness.Src;
@using NorthwindModel.Models;



<!DOCTYPE html>
@{
var customers = new CustomersBusiness();
    var table = customers.Get();
    Customer item = new Customer() { CustomerID = "Select...", CompanyName = "Select..." };
    table.Insert(0, item);
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShoppingCreate</title>

</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ShoppingCart</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CustomerID, new SelectList(table), new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    <span id="text-counter">0/100</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">
        $('#Description').keyup(function () {
            //alert('testo digitado')
            var text = $(this).val();
            var maxlen = 100;
            var count = text.length;
            for (var i = 0; i < text.length; i++) {
                if (text[i] == '\n')
                    count++;
            }
            $('#text-counter').html(count + '/' + maxlen);
        });
    </script>

</body>
</html>

NorthwindMVC/NorthwindMVC/Views/Shopping/ShoppingCreate.cshtml
@model NorthwindModel.Models.ShoppingCart
@using NorthwindBusiness.Src;
@using NorthwindModel.Models;

@{
    ViewBag.Title = "ShoppingCreate";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
}

<h2>ShoppingCreate</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ShoppingCart</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CustomerID, (IEnumerable<SelectListItem>)ViewBag.Customers, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.PurchaseDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
            @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            <span id="text-counter">0/100</span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ShoppingIndex")
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/Mascaras")
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">
        $('#Description').keyup(function () {

            var text = $(this).val();
            var maxlen = 100;
            var count = text.length;
            for (var i = 0; i < text.length; i++) {
                if (text[i] == '\n')
                    count++;
            }
            $('#text-counter').html(count + '/' + maxlen);
        });
    </script>
}

NorthwindMVC/NorthwindMVC/Views/Shopping/ShoppingDelete.cshtml
@model NorthwindModel.Models.ShoppingCart

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>



    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ShoppingCartID)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |

        </div>
    }
    @Html.ActionLink("Back to List", "ShoppingIndex")
</div>

NorthwindMVC/NorthwindMVC/Views/Shopping/ShoppingEdit.cshtml
@model NorthwindModel.Models.ShoppingCart
@using NorthwindBusiness.Src;
@using NorthwindModel.Models;

@{
    ViewBag.Title = "ShoppingEdit";
}

<h2>ShoppingEdit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ShoppingCart</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ShoppingCartID)

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CustomerID, (IEnumerable<SelectListItem>)ViewBag.Customers, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.PurchaseDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
            @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            <span id="text-counter">0/100</span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ShoppingIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">
        //conta caracteres no evento OnKeyUp do TextArea
        $('#Description').keyup(function () {
            updateTextCounter($(this).val());
        });
        //conta caracteres no evento OnReady do document
        $(document).ready(function () {
            updateTextCounter($('#Description').val());
        });
        //conta caracteres
        function updateTextCounter(text) {            
            var maxlen = 100;
            var count = text.length;
            for (var i = 0; i < text.length; i++) {
                if (text[i] == '\n')
                    count++;
            }
            $('#text-counter').html(count + '/' + maxlen);
        }
    </script>
}

NorthwindMVC/NorthwindMVC/Views/Shopping/ShoppingIndex.cshtml
@model IEnumerable<NorthwindBusiness.Src.ShoppingCartExtend>

@{
    ViewBag.Title = "ShoppingIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ShoppingIndex</h2>

<p>
    @Html.ActionLink("Create New", "ShoppingCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ShoppingCartID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ShoppingCartID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PurchaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "ShoppingEdit", new { id = item.ShoppingCartID }) |
            @Html.ActionLink("List", "ShoppingItemIndex", "ShoppingItem", new { id = item.ShoppingCartID },null) |
            @Html.ActionLink("Delete", "ShoppingDelete", new { id = item.ShoppingCartID })
        </td>
    </tr>
}

</table>