NorthwindMVC/NorthwindMVC/Controllers/ShoppingController.cs
using NorthwindBusiness.Src;
using NorthwindModel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NorthwindMVC.Controllers
{
    public class ShoppingController : Controller
    {
        private ShoppingCartBusiness shoppingCartList = new ShoppingCartBusiness();
        /*!
         * Lista de produtos
         */
        public ActionResult ShoppingIndex()
        {
            List<ShoppingCartExtend> list = shoppingCartList.SelectList();
            return View(list);
        }
        /*!
         * 
         */
        private List<SelectListItem> CreateCustomerList()
        {
            var custumers = new CustomersBusiness();
            var table = custumers.SelectList();
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "Select...", Value = "0" });
            foreach (var item in table)
                list.Add(new SelectListItem() { Text = item.CompanyName, Value = item.CustomerID });
            return list;
        }
        /*!
         * Cria novo produto 
         */
        public ActionResult ShoppingCreate()
        {            
            ViewBag.Customers = CreateCustomerList();
            //
            var shoppingCart = new ShoppingCart();
            return View(shoppingCart);
        }
        /*!
         * Valida e adiciona novo produto na lista 
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingCreate(ShoppingCart shoppingCart)
        {
            //validacoes
            if (shoppingCart.CustomerID == "0")
            {
                ModelState.AddModelError("CustomerID", "Selecione opção a customer.");
            }            
            if (shoppingCart.Description.Length > 100)
            {
                ModelState.AddModelError("Description", "Descrição deve ter no maximo 100 caracteres.");
            }
            if (ModelState.IsValid)
            {
                shoppingCartList.InsertItem(shoppingCart);
                return RedirectToAction("ShoppingIndex");
            }
            else
            {
                ViewBag.Customers = CreateCustomerList();
                return View("ShoppingCreate", shoppingCart);                
            }
        }

        public ActionResult ShoppingEdit(int id)
        {
            ViewBag.Customers = CreateCustomerList();
            var item = shoppingCartList.SelectItem(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingEdit(ShoppingCart shoppingCart)
        {
            //validacoes
            if (shoppingCart.CustomerID == "0")
            {
                ModelState.AddModelError("CustomerID", "Selecione opção a customer.");
            }
            if (ModelState.IsValid)
            {
                shoppingCartList.UpdateItem(shoppingCart);
                return RedirectToAction("ShoppingIndex");
            }
            else
            {
                return View("ShoppingEdit", shoppingCart);
            }
        }

        public ActionResult ShoppingDelete(int id)
        {
            var item = shoppingCartList.SelectItem(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingDelete(ShoppingCart shoppingCart)
        {
            shoppingCartList.DeleteItem(shoppingCart.ShoppingCartID);
            return RedirectToAction("ShoppingIndex");
        }

        



    }
}

NorthwindMVC/NorthwindMVC/Controllers/ShoppingItemController.cs
using NorthwindBusiness.Src;
using NorthwindModel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NorthwindMVC.Controllers
{
    public class ShoppingItemController : Controller
    {
        private static int shoppingCartID;
        /*!
         * Mostra lista de items
         * @param id: identificador do carrinho de compras
         */
        public ActionResult ShoppingItemIndex(int id)
        {
            shoppingCartID = id;
            var shoppingCartBusiness = new ShoppingCartItemBusiness(shoppingCartID);
            var list = shoppingCartBusiness.SelectList();
            return View(list);
        }

        private void SetupView()
        {
            ViewBag.ShoppingCartID = shoppingCartID;
            var list1 = CreateCategoryList();
            list1[indexCategory].Selected = true;
            ViewBag.Categories = list1;
            ViewBag.Products = CreateProductList(indexCategory);
        }

        public ActionResult ShoppingItemCreate()
        {
            SetupView();
            var item = new ShoppingCartItem();            
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingItemCreate(ShoppingCartItem shoppingCartitem)
        {
            //validaçoes servidor
            var shoppingCartItemBusiness = new ShoppingCartItemBusiness(shoppingCartID);
            if (shoppingCartitem.ProductID == 0)
            {
                ModelState.AddModelError("ProductID", "Selecione um produto.");
            }
            if (shoppingCartitem.Quantity == 0)
            {                
                ModelState.AddModelError("Quantity", "Especifique a quantidade.");
            }
            if (ModelState.IsValid)
            {
                var productBusiness = new ProductsBusiness();
                var product = productBusiness.SelectItem(shoppingCartitem.ProductID);
                shoppingCartitem.UnitPrice = product.UnitPrice;
                shoppingCartitem.ShoppingCartID = shoppingCartID;
                shoppingCartItemBusiness.InsertItem(shoppingCartitem);
                return RedirectToAction("ShoppingItemIndex", new { id = shoppingCartID });
            }
            else
            {
                SetupView();
                return View("ShoppingItemCreate", shoppingCartitem);
            }
        }

        public ActionResult ShoppingItemEdit(int id1, int id2)
        {
            //ShoppingCartItem item = new ShoppingCartItem();
            //if (id.HasValue)
            //{
            //    var products = new ProductsBusiness();
            //    var product = products.SelectItem(id.Value);
            //    //item.ProductID = product.ProductID;
            //    //item.UnitPrice = product.UnitPrice;
            //}
            ViewBag.ShoppingCartID = shoppingCartID;

            var shoppingCart = new ShoppingCartItemBusiness(shoppingCartID);
            //ShoppingCartItem item = shoppingCart.SelectItem(id1);
            //if (id2 != 0)
            //{
            //    var products = new ProductsBusiness();
            //    var product = products.SelectItem(id2);
            //    //item.ProductID = product.ProductID;
            //    //item.UnitPrice = product.UnitPrice;
            //}
            //return View(item);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShoppingItemEdit(ShoppingCartItem shoppingCartitem)
        {
            var shoppingCart = new ShoppingCartItemBusiness(shoppingCartID);
            shoppingCart.InsertItem(shoppingCartitem);
            return RedirectToAction("ShoppingItemIndex", new { id = shoppingCartID });
        }
        
        private static int indexCategory = 0;

        public ActionResult ShoppingItemSetProductID(int id)
        {
            indexCategory = id;            
            return RedirectToAction("ShoppingItemCreate");            
        }

        [HttpGet]
        public JsonResult ShoppingItemSetProductIdJson(int id)
        {
            indexCategory = id;            
            var list = CreateProductList(indexCategory);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        private List<SelectListItem> CreateCategoryList()
        {
            var category = new CategoriesBusiness();
            var table = category.SelectList();
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "All", Value = "0" });
            foreach (var item in table)
                list.Add(new SelectListItem() { Text = item.CategoryName, Value = item.CategoryID.ToString() });
            return list;
        }

        public List<SelectListItem> CreateProductList(int id)
        {
            var products = new ProductsBusiness();
            List<Product> list1 = new List<Product>();
            if (id == 0)
                list1 = products.SelectList();
            else
                list1 = products.SelectListByCategory(id);
            var list2 = new List<SelectListItem>();
            list2.Add(new SelectListItem() { Text = "Select", Value = "0" });
            foreach (var item in list1)
                list2.Add(new SelectListItem() { Text = item.ProductID.ToString("000") +"-"+ item.ProductName + "[" + item.UnitPrice + "]", Value = item.ProductID.ToString() });
            return list2;
        }

        [HttpGet]
        public JsonResult GetProductInfo(int id)
        {
            var products = new ProductsBusiness();
            var list = products.SelectListInfo(id);
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

NorthwindMVC/NorthwindMVC/Views/ShoppingItem/ProductListPartial.cshtml
<div>PRODUCT LIST BY CATEGORY</div>
<div style="overflow: auto; height:400px;">
    <table id="tableRight" border="1" class="table table-bordered table-condensed table-hover table-striped">
        <thead>
            <tr style="height:25px;">
                <th>ProductID</th>
                <th>ProductName</th>
                <th>UnitPrice</th>
            </tr>
        </thead>
        <tbody id="tableRightBody" style="overflow: auto;  height: 200px;"></tbody>
    </table>
</div>

NorthwindMVC/NorthwindMVC/Views/ShoppingItem/ShoppingItemCreate.cshtml
@model NorthwindModel.Models.ShoppingCartItem
@using NorthwindBusiness.Src;
@using NorthwindModel.Models;
@{
    ViewBag.Title = "ShoppingItemCreate";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";//necessario para funcionamento dos scripts
}

<h2>ShoppingItemCreate. ShoppingCartID = @ViewBag.ShoppingCartID</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ShoppingCartItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <table id="table1" border="1" style="width:100%">
            <tr>
                <td style="width:50%" valign="top">
                    <table id="tableLeft" border="1" style="width:100%">
                        <tr>
                            <td>
                                <div class="form-group">
                                    @Html.Label("Category", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("ddlCategoryID", (IEnumerable<SelectListItem>)ViewBag.Categories, new { required = "required", @onchange = "ddlCategoryID_Change();" })
                                        <span id="teste">0</span>

                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">

                                    @Html.LabelFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2", value = ViewBag.ProductID })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.ProductID, (IEnumerable<SelectListItem>)ViewBag.Products, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td align="center">
                                <div class="form-group">
                                    @*<div class="col-md-offset-2 col-md-10">*@
                                    <input id="button1" type="submit" value="Create" class="btn btn-default" />
                                    @*</div>*@
                                </div>
                            </td>
                        </tr>
                    </table>
                </td>
                <td valign="top">
                    @{
                        Html.RenderPartial("ProductListPartial");
                    }
                    @*<div style="overflow: auto; height:400px;">
            <table id="tableRight" border="1" class="table table-bordered table-condensed table-hover table-striped">
                <thead>
                    <tr style="height:25px;">
                        <th>ProductID</th>
                        <th>ProductName</th>
                        <th>UnitPrice</th>
                    </tr>
                </thead>
                <tbody id="tableRightBody" style="overflow: auto;  height: 200px;"></tbody>
            </table>
        </div>*@
                </td>
            </tr>
        </table>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ShoppingItemIndex", new { id = ViewBag.ShoppingCartID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript">
        $(window).on("load", function () {
            ddlCategoryID_Change();
        });

        function ddlCategoryID_Change() {
            var value = $("#ddlCategoryID").val();

            $("#teste").html(value);
            getProductList(value);

            $.ajax({
                url: "/ShoppingItem/ShoppingItemSetProductIdJson",
                data: { id: value },
                type: "GET",
                dataType: "json",
                success: function (result) {
                    $('#ProductID').empty();
                    $.each(result, function (i, item) {
                        $("#ProductID").append('<option value="' + item.Value + '">' +
                            item.Text + '</option>');
                    });

                },
                error: function (error) {
                    alert('error =' + error);
                }
            });


        }

        function getProductList(value) {
            $(document).ready(function () {
                
                //Call EmpDetails jsonResult Method
                $.getJSON("/ShoppingItem/GetProductInfo/?id=" + value,
                    function (json) {
                        var tr;
                        //Append each row to html table
                        $('#tableRightBody').empty();
                        for (var i = 0; i < json.length; i++) {
                            tr = $('<tr/>');
                            tr.append("<td>" + json[i].ProductID + "</td>");
                            tr.append("<td>" + json[i].ProductName + "</td>");
                            tr.append("<td>" + json[i].UnitPrice + "</td>");
                            $('#tableRightBody').append(tr);
                        }
                    });
            });
        }

    </script>
}

NorthwindMVC/NorthwindMVC/Views/ShoppingItem/ShoppingItemEdit.cshtml
@model NorthwindModel.Models.ShoppingCartItem
@using NorthwindBusiness.Src;
@using NorthwindModel.Models;
@{
    ViewBag.Title = "ShoppingItemEdit";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
}
@{
    var category = new CategoriesBusiness();
    var table = category.SelectList();
    var list = new List<SelectListItem>();
    list.Add(new SelectListItem() { Text = "All", Value = "0" });
    foreach (var item in table)
    {
        list.Add(new SelectListItem() { Text = item.CategoryName, Value = item.CategoryID.ToString() });
    }
}
<h2>ShoppingItemEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>ShoppingCartItem</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ShoppingCartItemID)
   
    <div class="form-group">
        @Html.Label("Category", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ddlCategoryID", list, new { htmlAttributes = new { @class = "form-control" } })
            <span id="teste">0</span>
            <br />
            <input id="ProductList" type="button" value="Product List" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProductID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ShoppingItemIndex", new { id = ViewBag.ShoppingCartID })
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">

        $("#ddlCategoryID").change(function () {
            var value = $(this).val();
            $("#teste").html(value);
        });
        //
        $("#ProductList").click(function () {
            var value1 = $("#ddlCategoryID").val();
            var value2 = $("#ShoppingCartItemID").val();
            var url = "/ShoppingItem/ShoppingItemProductList?id1=" + value1 + "&id2=1" + "&id3=" + value2;
            location.href = url;

            //alert('clique no botão com valor ' + url);
            //$.ajax({
            //    url: "/Shopping/ShoppingItemProductList",
            //    data: { id: value },
            //    type: "GET",
            //    dataType: "html",
            //    success: function (dados) {
            //        },
            //    error: function (erro) {
            //        alert('erro ='+erro);}
            //});

        });
    </script>
}

NorthwindMVC/NorthwindMVC/Views/ShoppingItem/ShoppingItemIndex.cshtml
@model IEnumerable<NorthwindBusiness.Src.ShoppingCartItemExtend>

@{
    ViewBag.Title = "ShoppingItemIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ShoppingItemIndex</h2>

<p>
    @Html.ActionLink("Create New", "ShoppingItemCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ShoppingCartID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ShoppingCartID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>        
        <td>
            @Html.ActionLink("Edit", "ShoppingItemEdit", new { @id1 = item.ShoppingCartItemID , @id2 = 0 }) |            
            @Html.ActionLink("Delete", "Delete", new { id = item.ShoppingCartItemID })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Shopping List", "ShoppingIndex", "Shopping")
</p>

NorthwindMVC/NorthwindMVC/Views/ShoppingItem/ShoppingItemProductList.cshtml
@model IEnumerable<NorthwindModel.Models.Product>
@using NorthwindModel.Models;
@{
    ViewBag.Title = "ShoppingItemProductList";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
}

<h2>ShoppingItemProductList</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductID)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>        
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductID)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </td>           
            <td>
               
                       <input type="button" value="Select" onclick="selectProductToCreate('@item.ProductID')" />
                   
                        @*<input type="button" value="Select" onclick="selectProductToEdit('@ViewBag.ShoppingCartItemID','@item.ProductID')" />*@
                    
                            
            </td>
        </tr>
    }
</table>
@section Scripts {
    <script type="text/javascript">
        //
        //function selectProductToCreate(id) {
        //    var url = "/ShoppingItem/ShoppingItemSetProductID?id=" + id;
        //    location.href = url;
        //}
        ////
        //function selectProductToEdit(id1, id2) {
        //    var url = "/ShoppingItem/ShoppingItemEdit?id1=" + id1 + "&id2=" + id2;
        //    location.href = url;
        //}
    </script>
}